# Generated by Django 5.1 on 2024-08-20 10:52

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_unit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(choices=app.models.Unit.get_unit_choices, default='pieces', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opening_stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
