# Generated by Django 5.1 on 2024-08-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
