# Generated by Django 5.1 on 2024-08-22 11:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_user_stockmovement_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.CharField(max_length=255)),
                ('panno', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['vendor'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='name',
            field=models.CharField(choices=app.models.Product.get_product_choices, max_length=255),
        ),
    ]
