# Generated by Django 5.1 on 2024-08-22 11:42

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_vendor_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='vendor',
            field=models.CharField(blank=True, choices=app.models.Vendor.get_vendor_choices, max_length=255, null=True),
        ),
    ]
