# Generated by Django 5.1 on 2024-08-22 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_stockmovement_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
