# Generated by Django 5.1 on 2024-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_stockmovement_name_alter_stockmovement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
