# Generated by Django 5.1 on 2024-08-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_stockmovement_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
