# Generated by Django 5.1 on 2024-08-23 05:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_stockmovement_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='unit',
            field=models.CharField(choices=app.models.Unit.get_unit_choices, max_length=255),
        ),
    ]
