# Generated by Django 5.1 on 2024-08-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_stockmovement_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='opid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
