# Generated by Django 5.1 on 2024-08-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_stockmovement_opid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='opid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product', unique=True),
        ),
    ]
