# Generated by Django 5.1 on 2024-08-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_stockmovement_opid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='opid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
