# Generated by Django 5.1 on 2024-08-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_stockmovement_opid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='pdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
