# Generated by Django 5.1 on 2024-08-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_stockmovement_pdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
