# Generated by Django 5.1 on 2024-09-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_holdsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdsale',
            name='channel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
