# Generated by Django 5.1 on 2024-09-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_holdsale_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
