# Generated by Django 5.1 on 2024-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_stockmovement_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectionsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('mode', models.TextField()),
            ],
        ),
    ]
