# Generated by Django 5.1 on 2024-09-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_collectionsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionsale',
            name='mode',
            field=models.CharField(max_length=20),
        ),
    ]
