# Generated by Django 5.1 on 2024-10-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_collectionsale_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='payment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collectionsale',
            name='mode',
            field=models.CharField(max_length=255),
        ),
    ]
