# Generated by Django 5.1 on 2024-10-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_profile_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='user',
        ),
    ]
