# Generated by Django 5.1 on 2024-10-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_rename_user_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='User',
            new_name='user',
        ),
    ]
